### ISSUE TITLE
Dajngo 2.0 support

### ISSUE THREAD

**Issue by pjmcdermott** [peterbe/django-html-validator#41]
Does not work with Django 2.0. For instance, `MIDDLEWARE_CLASSES` used in `client.py`, line 24 not longer supported.

    File "/home/paul/.virtualenvs/Syncables/lib/python3.5/site-packages/htmlvalidator/client.py", line 24, in get
        in settings.MIDDLEWARE_CLASSES
      File "/home/paul/.virtualenvs/Syncables/lib/python3.5/site-packages/django/conf/__init__.py", line 57, in __getattr__
        val = getattr(self._wrapped, name)
    AttributeError: 'Settings' object has no attribute 'MIDDLEWARE_CLASSES'
